### PR TITLE
[Go] Improve numbers parsing performance

### PR DESCRIPTION
**Pull request by deathaxe**
This commit ...

1. scopes decimal imaginary numbers as `constant.numeric.imaginary.decimal.go`
2. merges the match rules for numbers so is only one rule per number type in order to improve parsing performance. 
3. replaces `{{ohdigits}}` variable by `{{hdigits}}?`.
4. The `dec_exponent` and `hex_exponent` variables are introduced to
shorten the match patterns and to create some similarities to the other
syntaxes like OCaml, Lua, etc. .

The parsing performance is increased by round about 6%.

Benchmark was done with a file of 10k lines of code with all the
numbers test cases.

Benchmark was done with a mix of numbers:

```
0; 123456789; -0; -123456789; 1777_000_000;
0_1.0_1; 1_23.4_6;
0b1011; 0B00001; -0b1; 0b_1; 0B1_0;
0b1011i; 0B00001i; 0b_1011i; 0B000_01i;
0e+0; 0E+0; 0.0e+0; 0.0E+0; 123.456e+789;
0e-0; 0E-0; 0.0e-0; 0.0E-0; 123.456e-789;
0o660; 0O061; -0o02; 0o_660; 0O0_6_1;
0o6i; 0O35i; 0o_6i; 0O3_5i;
0x0; 0x0123456789ABCDEFabcdef; -0x0123456789ABCDEFabcdef;
0x0i; 0x0123456789ABCDEFabcdefi; 0x_012_CD_Efi;
0x1.0P-1021; 0X1.0p-1021;
0x1p-2; 0X1P+2; 0x1p2;
0x1p-2i; 0x1.0P-1021i; 0x1.Fp+0i;
0x2.p10; 0x1.Fp+0; 0X.8p-0;
0x_0; 0x012_3456_7_8_9ABCDEFabcd_ef;
0x_1_1.0_7P-1_021;
0x_1p-2; 0X1_1P+2; 0x_1p2_1;
0x_1p-2i; 0x1_4.0_5P-102_1i;
0x_2.p1_0; 0x1.F_Ap+0;
10
123.456i; -123.456i; 1_23.45_6i;
1_1e+2_1i; 1.2_1E-3_5i;
1_2e+0; 1E+0_1; 0.1_2e2; 1_23.4_56e+78_9;
1e+2i; 1e-2i; 1.2e+3i; 1.2e-3i; 1E+2i; 1E-2i; 1.2E+3i; 1.2E-3i;
000.000; 123.456; .0; 1.;
000i; 100i; -100i; 1_1i;
00; 01234567; -01234567; 0_0; 012_45;
08; 09;
```

### CODE REVIEW

**Comment by deathaxe** [comment]
You propably should add a reference to the original https://github.com/sublimehq/Packages/pull/2123 to auto-close the issue #1852 after it was merged to master.

Reason: commit c34ac93

**Comment by wbond** [comment]
@deathaxe I merged your branch in to sublimehq/Packages master, thanks!

**Comment by patrickrgaffney** [comment]
Thanks @deathaxe!

How did you run the performance tests? Is that with the `Syntax Tests - Performance` command palette item?

**Comment by deathaxe** [comment]
Yes, it is.

I always create some kind of hopefully general enough test snippets like a line of all possible variations of numbers and than duplicate it to get a file of about 10k of lines. Sometimes I just duplicate an existing file of code with many different stuff in it to get an idea of the performance hits of different possible solutions.

This file is then saved as `syntax_test_perf_foo.go` and used to run the `Syntax Tests - Performance` against.

EDIT: You need to be careful with the results as sometimes ST does mess up the regex cache files if a sublime-syntax is modified too quickly and too often, which can result in wrong results.

**Pull request closed without merging**
